static const GMeasurementAmplitudeCalibrationRow s_AmplitudeCalibrationRows[] =
{
    {   10000.0f, 5U, {
        {   1596.8040f,  25.0000f },  // sigma ~= 0.0230 mV
        {   3200.5640f,  50.0000f },  // sigma ~= 0.0067 mV
        {   4807.7880f,  75.0000f },  // sigma ~= 0.0053 mV
        {   6408.6155f, 100.0000f },  // sigma ~= 0.0052 mV
        {   8010.0945f, 125.0000f },  // sigma ~= 0.0058 mV
    } },
};

/* worst one-frame equivalent peak noise: 0.022992 mV */
