static const GMeasurementAmplitudeCalibrationRow s_AmplitudeCalibrationRows[] =
{
    {  100000.0f, 5U, {
        {   1584.5795f,  25.0000f },  // sigma ~= 0.0305 mV
        {   3160.6655f,  50.0000f },  // sigma ~= 0.0487 mV
        {   4747.4735f,  75.0000f },  // sigma ~= 0.0546 mV
        {   6328.4730f, 100.0000f },  // sigma ~= 0.0369 mV
        {   7906.0425f, 125.0000f },  // sigma ~= 0.0327 mV
    } },
};

/* worst one-frame equivalent peak noise: 0.054639 mV */
